version: 3

services:
  db:
    image: tutum/mongodb:3.0
    ports:
      - '27017:27017'
      - '28017:28017'
    restart: always
    volumes:
      - db:/data/db
    env_file:
      - ./variables.env

volumes:
  db:
